plugins:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "test/**/*"
    - "*.gemspec"
    - "lib/brainiac/plugins/zoho.rb"
  CountAsOne:
    - heredoc

Metrics/MethodLength:
  Max: 75
  Exclude:
    - "lib/brainiac/plugins/zoho.rb"

Metrics/AbcSize:
  Max: 90
  Exclude:
    - "lib/brainiac/plugins/zoho.rb"

Metrics/CyclomaticComplexity:
  Max: 18

Metrics/PerceivedComplexity:
  Max: 18

Metrics/ModuleLength:
  Max: 800
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Max: 800
  Exclude:
    - "test/**/*"

Metrics/BlockNesting:
  Max: 5

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: false

Style/TopLevelMethodDefinition:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Layout/LineLength:
  Max: 150

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/SuppressedException:
  AllowComments: true
